### ISSUE TITLE
Players can go off the map even though the pathfinding grid is the same size as the map

### ISSUE THREAD

**Issue by emmalevesque** [pwrstudio/eyebeam-frontend#10]
Clicking outside of the map area doesn't prevent the player from moving into the blank space outside the grid, the pathfinding grid is sized to exactly the same size and shape of the grid so this shouldn't be happening. Is there a reason these don't match up?

**Comment by pwrstudio** [comment]
Sorry, I think I forgot to mention: the pathfinding image should in fact be ten times smaller than the main map texture! So 400x400 pixels.

<img width="1181" alt="Screenshot 2021-02-16 at 13 59 49" src="https://user-images.githubusercontent.com/8209990/108066529-bffa7b80-705f-11eb-8cf2-a73f4aaba152.png">

I scaled it down and re-uploaded now, and seems to work.
