### ISSUE TITLE
Spritesheet Generation Issue

### ISSUE THREAD

**Issue by madpenny** [pwrstudio/eyebeam-frontend#2]
Not sure why the spritesheet will not generate? 

<img width="632" alt="Screen Shot 2021-02-04 at 3 51 38 PM" src="https://user-images.githubusercontent.com/31375201/106954285-8fcae880-6701-11eb-92b7-5ae45a6dd45f.png">

**Comment by emmalevesque** [comment]
looking at the error console after producing this error we get the following message:

`Access to fetch at 'https://eyebeam-graphics.post-rational.org/project' from origin 'https://eyebeam.sanity.studio' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by pwrstudio** [comment]
Strange, It does work for me. Could you check that this problem persists for you? And what browser do you use to access the sanity CMS?

**Comment by madpenny** [comment]
It's not working on Chrome or Firefox for me

**Comment by emmalevesque** [comment]
Tried in safari as well and received a slightly more detailed error:

`TypeError: Origin https://eyebeam.sanity.studio is not allowed by Access-Control-Allow-Origin.`

**Comment by emmalevesque** [comment]
Following up on this. I was able to get the sprite sheet to generate using the existing 8bit sprite from the previous instance of this app. I'm going to play around with our new sprite files a bit and see if i can find a way around this issue. Thank you!

**Comment by emmalevesque** [comment]
I was able to upload these new sprites. It seems the fix was that I needed to convert the frame images to 8-bit sRGB pngs :)
