### ISSUE TITLE
Chatbox not working 

### ISSUE THREAD

**Issue by madpenny** [pwrstudio/eyebeam-frontend#3]
Went to test the chatbox, and comments are not showing up @pwrstudio 
<img width="465" alt="Screen Shot 2021-02-08 at 12 09 15 PM" src="https://user-images.githubusercontent.com/31375201/107255918-cd33bc80-6a06-11eb-9bb0-5b9039baef55.png">

**Comment by pwrstudio** [comment]
Caused by update to the sanity CMS. Should be fixed by this commit:
https://github.com/pwrstudio/eyebeam-frontend/commit/5ad57bb7b0173dab470066589170d012faa9f070
