### ISSUE TITLE
Avatar issues: Getting errors when "Saturn V" avatar isn't included in the Set

### ISSUE THREAD

**Issue by emmalevesque** [pwrstudio/eyebeam-frontend#9]
I'm trying to add a new default avatar and I've done my best to copy the settings from the "Saturn V" avatar from the previous instance.

The sprite sheets generate fine and I publish them without errors. But when I remove the "Saturn V" avatar from the set and try to reload the page I get the following error:

`Uncaught TypeError: Cannot read property 'animations' of undefined`
`World.svelte:497`

I'm doing some investigation in the source code now, but if you could take a look we would appreciate it!

**Comment by pwrstudio** [comment]
I think this could be due to somebody, being assigned the Saturn V avatar before it was removed, was active on the page.

I removed the Saturn-avatar from the list now and seems to work. 

Let me know if this problem presists/re-appear.
